language: node_js
node_js:
  - "7"

install: yarn install
cache: yarn

script: yarn build

deploy:
  provider: surge
  project: ./build/
  domain: sequencer.surge.sh
  on: master
  skip_cleanup: true
